Repository uni-helper/create-uni, pull requests merged in 2024-11, with the labels that each got.

#73 feat: add wot-demo as a template
  README.md
  src/question/template/templateDate.ts
Labels: size/S

#74 chore: update deps
  template/UI/ano/package.json
  template/UI/nut/package.json
  template/UI/uni/package.json
  template/config/lint/package.json
  template/config/typescript/package.json
  template/module/pinia/package.json
Labels: size/S

#75 chore: update deps
  template/UI/wot/package.json
  template/base/package.json
  template/config/typescript/package.json
  template/module/unocss/package.json
Labels: size/S

#76 chore: update deps
  template/UI/ano/package.json
  template/base/package.json
  template/config/lint/package.json
  template/module/unocss/package.json
Labels: size/S

#72 feat: add `uni-ku-root` plugin
  .github/workflows/ci.yml
  README.md
  src/question/plugin/choices.ts
  template/UI/uni/vite.config.js.data.mjs
  template/plugin/import/package.json
  template/plugin/root/package.json
  template/plugin/root/src/App.ku.vue
  template/plugin/root/vite.config.js.data.mjs
Labels: size/L

#77 chore: update deps
  template/UI/wot/package.json
  template/config/typescript/package.json
Labels: size/XS
