Repository uni-helper/create-uni, pull requests merged in 2024-12, with the labels that each got.

#78 chore: update deps
  template/UI/ano/package.json
  template/base/package.json
  template/config/lint/package.json
  template/config/typescript/package.json
  template/module/pinia/package.json
Labels: size/M

#80 feat: 新增 unisave 快速启动模版
  README.md
  src/question/template/templateDate.ts
Labels: size/S

#79 chore: update deps
  template/UI/ano/package.json
  template/UI/wot/package.json
  template/config/lint/package.json
  template/config/typescript/package.json
  template/module/pinia/package.json
  template/module/unocss/package.json
Labels: size/S

#81 chore: update deps
  template/config/typescript/package.json
Labels: size/XS
