Repository uni-helper/create-uni, pull requests merged in 2025-09, with the labels that each got.

#123 chore: update deps
  packages/core/template/UI/skiyee/package.json
  packages/core/template/config/lint/package.json
  packages/core/template/plugin/root/package.json
  pnpm-lock.yaml
Labels: size/XS

#132 fix: remove the renaming of manifest.json and the json5 dependency
  packages/core/package.json
  packages/core/src/index.ts
  packages/core/src/utils/index.ts
  packages/core/src/utils/jsonStringifyWithoutKeysQuotes.ts
  packages/core/src/utils/setPackageName.ts
  pnpm-lock.yaml
Labels: size/S

#135 chore: update deps
  packages/core/template/UI/ano/package.json
  packages/core/template/UI/nut/package.json
  packages/core/template/config/lint/package.json
  packages/core/template/config/typescript/package.json
  packages/core/template/plugin/import/package.json
  packages/core/template/plugin/pages/package.json
  packages/core/template/plugin/root/package.json
  pnpm-lock.yaml
Labels: size/S

#137 chore: update deps
  packages/core/template/UI/uview-pro/package.json
  packages/core/template/UI/wot/package.json
  packages/core/template/config/typescript/package.json
  packages/core/template/plugin/import/package.json
  packages/core/template/plugin/pages/package.json
  packages/core/template/plugin/root/package.json
Labels: size/S

#139 feat: add uni-echarts module
  .github/workflows/core_test.yml
  README.md
  packages/core/src/question/module/module.data.ts
  packages/core/template/module/uniEcharts/jsconfig.json.data.mjs
  packages/core/template/module/uniEcharts/package.json
  packages/core/template/module/uniEcharts/vite.config.js.data.mjs
  packages/mcp/src/handlers.ts
  packages/mcp/src/schemas.ts
  packages/mcp/src/types.ts
Labels: size/M
