Repository uni-helper/create-uni, pull requests merged in 2025-08, with the labels that each got.

#119 chore: update deps
  packages/core/template/config/lint/package.json
  packages/core/template/config/typescript/package.json
Labels: size/XS

#121 chore: update deps
  packages/core/template/UI/uni/package.json
  packages/core/template/UI/wot/package.json
  packages/core/template/base/package.json
  packages/core/template/config/lint/package.json
  packages/core/template/config/typescript/package.json
  packages/core/template/plugin/pages/package.json
  pnpm-lock.yaml
Labels: size/M

#122 docs: 更新模板列表中的wot-starter相关信息
  README.md
  packages/core/src/question/template/template.data.ts
Labels: size/S
