Repository uni-helper/create-uni, pull requests merged in 2025-10, with the labels that each got.

#140 feat(plugin): vite-plugin-component-placeholder
  .github/workflows/core_test.yml
  README.md
  packages/core/src/question/plugin/plugin.data.ts
  packages/core/template/plugin/componentPlaceholder/package.json
  packages/core/template/plugin/componentPlaceholder/vite.config.js.data.mjs
  packages/mcp/src/schemas.ts
  packages/mcp/src/types.ts
Labels: size/M

#141 chore: 修复 uni-echarts 参数名拼写错误
  README.md
Labels: size/XS

#142 fix(core): 修复 uni-uni 与 uni-echarts 自动导入冲突
  packages/core/template/UI/uni/vite.config.js.data.mjs
Labels: size/S

#143 chore(template): update the exclude pattern for the uni-ui resolver
  packages/core/template/UI/uni/vite.config.js.data.mjs
Labels: size/XS

#144 chore: update deps
  packages/core/template/UI/uview-pro/package.json
  packages/core/template/base/package.json
  packages/core/template/config/lint/package.json
  packages/core/template/config/typescript/package.json
  pnpm-lock.yaml
Labels: size/S
